name: anova_xarray_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - scipy
  - seaborn
  - statsmodels
  - ipykernel
  - numba
  - pandas
  - matplotlib
  - netcdf4
  - xarray
  - jupyterlab
  - numpy
  - dask
  - h5netcdf
  - zarr
  - notebook
  - cftime
  - bottleneck
  - myst-parser
  - black
  - ruff
  - sphinx-rtd-theme
  - mypy
  - pytest
  - sphinx
  - twine
  - pytest-cov
  - python-build
